coverage:
  range: 50..90 # coverage lower than 50 is red, higher than 90 green, between color code

  status:
    project: # settings affecting project coverage
      default:
        target: 70% # auto % coverage target

    # do not run coverage on patch nor changes
    patch: off